version: '3.8'

services:
  
  redis:
    image: redis:6
    expose:
      - "6379"
    environment:
      - TZ=${TZ}
    volumes:
      - redis_data:/data
    networks:
      - chat-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 300s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build:
      context: ./back
    expose:
      - "8000"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_URL=${REDIS_URL}
      - TZ=${TZ}
    networks:
      - chat-network
    restart: unless-stopped

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8005:80"
    environment:
      - TZ=${TZ}
    depends_on:
      - web
    networks:
      - chat-network
    restart: unless-stopped

volumes:
  # postgres_data 볼륨 제거
  redis_data:

networks:
  chat-network:
    driver: bridge
